name = "das"
compatibility_date = "2023-01-01"
account_id = "ec32767b7faa5f7325c21d238409d6f3"

[[r2_buckets]]
binding = "DAS_BUCKET"
bucket_name = "da-content"
preview_bucket_name = "da-content-preview"